USE [master]
GO
/****** Object:  Database [SpyDuh]    Script Date: 3/18/2023 9:35:35 AM ******/
CREATE DATABASE [SpyDuh]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'SpyDuh', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.SQLEXPRESS\MSSQL\DATA\SpyDuh.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'SpyDuh_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.SQLEXPRESS\MSSQL\DATA\SpyDuh_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT, LEDGER = OFF
GO
ALTER DATABASE [SpyDuh] SET COMPATIBILITY_LEVEL = 160
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [SpyDuh].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [SpyDuh] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [SpyDuh] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [SpyDuh] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [SpyDuh] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [SpyDuh] SET ARITHABORT OFF 
GO
ALTER DATABASE [SpyDuh] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [SpyDuh] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [SpyDuh] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [SpyDuh] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [SpyDuh] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [SpyDuh] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [SpyDuh] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [SpyDuh] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [SpyDuh] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [SpyDuh] SET  DISABLE_BROKER 
GO
ALTER DATABASE [SpyDuh] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [SpyDuh] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [SpyDuh] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [SpyDuh] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [SpyDuh] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [SpyDuh] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [SpyDuh] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [SpyDuh] SET RECOVERY SIMPLE 
GO
ALTER DATABASE [SpyDuh] SET  MULTI_USER 
GO
ALTER DATABASE [SpyDuh] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [SpyDuh] SET DB_CHAINING OFF 
GO
ALTER DATABASE [SpyDuh] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [SpyDuh] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [SpyDuh] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [SpyDuh] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO
ALTER DATABASE [SpyDuh] SET QUERY_STORE = ON
GO
ALTER DATABASE [SpyDuh] SET QUERY_STORE (OPERATION_MODE = READ_WRITE, CLEANUP_POLICY = (STALE_QUERY_THRESHOLD_DAYS = 30), DATA_FLUSH_INTERVAL_SECONDS = 900, INTERVAL_LENGTH_MINUTES = 60, MAX_STORAGE_SIZE_MB = 1000, QUERY_CAPTURE_MODE = AUTO, SIZE_BASED_CLEANUP_MODE = AUTO, MAX_PLANS_PER_QUERY = 200, WAIT_STATS_CAPTURE_MODE = ON)
GO
USE [SpyDuh]
GO
/****** Object:  Table [dbo].[AgencyLookup]    Script Date: 3/18/2023 9:35:35 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[AgencyLookup](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[Name] [nvarchar](255) NULL,
PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Assignment]    Script Date: 3/18/2023 9:35:36 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Assignment](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[Name] [nvarchar](255) NULL,
	[Location] [nvarchar](255) NULL,
	[StartTS] [datetime] NULL,
	[EndTS] [datetime] NULL,
	[IsUnderCover] [bit] NULL,
PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Countries]    Script Date: 3/18/2023 9:35:36 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Countries](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[CountryName] [nvarchar](255) NULL,
	[Region] [nvarchar](255) NULL,
PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Relationships]    Script Date: 3/18/2023 9:35:36 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Relationships](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[UserId] [int] NULL,
	[RelatedUserId] [int] NULL,
	[IsFriend] [bit] NULL,
PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[ServicesLookUp]    Script Date: 3/18/2023 9:35:36 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[ServicesLookUp](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[Name] [nvarchar](255) NULL,
PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[SkillsLookup]    Script Date: 3/18/2023 9:35:36 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[SkillsLookup](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[Name] [nvarchar](255) NULL,
PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Users]    Script Date: 3/18/2023 9:35:36 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Users](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[Name] [nvarchar](255) NULL,
	[EmailId] [int] NULL,
	[CountryId] [int] NULL,
	[UserName] [nvarchar](255) NULL,
	[Password] [nvarchar](255) NULL,
	[AgencyId] [int] NULL,
	[Type] [nvarchar](255) NULL,
	[HandlerId] [int] NULL,
	[AssignmentId] [int] NULL,
PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Users_Relationships]    Script Date: 3/18/2023 9:35:36 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Users_Relationships](
	[Users_Id] [int] NOT NULL,
	[Relationships_RelatedUserId] [int] NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[Users_Id] ASC,
	[Relationships_RelatedUserId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[UserServices]    Script Date: 3/18/2023 9:35:36 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[UserServices](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[UserId] [int] NULL,
	[ServiceId] [int] NULL,
	[AvalibleToHire] [bit] NULL,
PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[UserSkills]    Script Date: 3/18/2023 9:35:36 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[UserSkills](
	[id] [int] IDENTITY(1,1) NOT NULL,
	[UserId] [int] NULL,
	[SkillId] [int] NULL,
	[Expertise] [nvarchar](255) NULL,
PRIMARY KEY CLUSTERED 
(
	[id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[Relationships]  WITH CHECK ADD FOREIGN KEY([RelatedUserId])
REFERENCES [dbo].[Users] ([Id])
GO
ALTER TABLE [dbo].[Relationships]  WITH CHECK ADD FOREIGN KEY([UserId])
REFERENCES [dbo].[Users] ([Id])
GO
ALTER TABLE [dbo].[Users]  WITH CHECK ADD FOREIGN KEY([AgencyId])
REFERENCES [dbo].[AgencyLookup] ([Id])
GO
ALTER TABLE [dbo].[Users]  WITH CHECK ADD FOREIGN KEY([AssignmentId])
REFERENCES [dbo].[Assignment] ([Id])
GO
ALTER TABLE [dbo].[Users]  WITH CHECK ADD FOREIGN KEY([CountryId])
REFERENCES [dbo].[Countries] ([Id])
GO
ALTER TABLE [dbo].[Users]  WITH CHECK ADD FOREIGN KEY([HandlerId])
REFERENCES [dbo].[Users] ([Id])
GO
ALTER TABLE [dbo].[UserServices]  WITH CHECK ADD FOREIGN KEY([ServiceId])
REFERENCES [dbo].[ServicesLookUp] ([Id])
GO
ALTER TABLE [dbo].[UserServices]  WITH CHECK ADD FOREIGN KEY([UserId])
REFERENCES [dbo].[Users] ([Id])
GO
ALTER TABLE [dbo].[UserSkills]  WITH CHECK ADD FOREIGN KEY([SkillId])
REFERENCES [dbo].[SkillsLookup] ([Id])
GO
ALTER TABLE [dbo].[UserSkills]  WITH CHECK ADD FOREIGN KEY([UserId])
REFERENCES [dbo].[Users] ([Id])
GO
USE [master]
GO
ALTER DATABASE [SpyDuh] SET  READ_WRITE 
GO
